version: '3.3'
services:
  mongo:
    image: mongo
    container_name: "db-barang"
    restart: always
    environment:
      MONGO_INITDB_ROOT_DATABASE: db-barang
    volumes:
      - './dockervolume/mongodb:/data/db'
    ports:
      - 27017:27017

  app:
    container_name: 'service-barang'
    image: devkotakjualan/service-barang
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - 'mongo'

networks:
  WServiceRejectNetwork:
    driver: bridge
